package bot.entity.constans;

public enum State {

	STATE_GET_STARTED,
	STATE_NEW_POLICY,
	STATE_APP_NAME,
	STATE_EMAIL,
	STATE_ADDRESS,
	STATE_EDIT_APP_NAME_POST,
	STATE_EDIT_EMAIL_POST,
	STATE_EDIT_ADDRESS_POST,
	STATE_EDIT_APP_NAME,
	STATE_EDIT_EMAIL,
	STATE_EDIT_ADDRESS,
	STATE_NOT_FOUND_POLICY,
	STATE_MESSAGE_GENERIC,
	STATE_FINISH;
}
